import enum


class AssetStatus(str, enum.Enum):
    AVAILABLE = "AVAILABLE"
    ASSIGNED = "ASSIGNED"
    IN_MAINTENANCE = "IN_MAINTENANCE"
    RETIRED = "RETIRED"
    DISPOSED = "DISPOSED"


class AllocationAction(str, enum.Enum):
    ASSIGN = "ASSIGN"
    RETURN = "RETURN"
    REASSIGN = "REASSIGN"


class MaintenanceType(str, enum.Enum):
    PREVENTIVE = "PREVENTIVE"
    CORRECTIVE = "CORRECTIVE"
    INSPECTION = "INSPECTION"
    UPGRADE = "UPGRADE"
    OTHER = "OTHER"


class MaintenanceStatus(str, enum.Enum):
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class NotificationSeverity(str, enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"
    SUCCESS = "SUCCESS"


class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    MANAGER = "MANAGER"
    VIEWER = "VIEWER"


class NotificationType(str, enum.Enum):
    HEALTH_DRIFT = "HEALTH_DRIFT"
    POLICY_AUTO_MAINTENANCE = "POLICY_AUTO_MAINTENANCE"
    HIGH_RISK = "HIGH_RISK"
    WARRANTY_EXPIRING = "WARRANTY_EXPIRING"
    MAINTENANCE_DUE = "MAINTENANCE_DUE"
    HEALTH_IMPROVED = "HEALTH_IMPROVED"
    INSPECTION_PASSED = "INSPECTION_PASSED"
    MAINTENANCE_COMPLETED = "MAINTENANCE_COMPLETED"
    TRANSFER_COMPLETED = "TRANSFER_COMPLETED"
    WARRANTY_RENEWED = "WARRANTY_RENEWED"
    RISK_REDUCED = "RISK_REDUCED"

